#!/usr/bin/env python3
"""
Generate src/data/randomizer/bst_table.h -- base stat total (BST) for
every species, used by the BST-restricted trainer randomizer (a
substitute must be within +10% / -10% of the original's BST, widened
to -20% if the original's BST exceeds 650, since very few non-
legendary species exceed that and a narrow window could otherwise come
up empty for something like Slaking).

Usage (from repo root):
    python3 tools/randomizer/generate_bst_table.py
"""
import json
from pathlib import Path

SPECIES_POOL_PATH = Path("tools/randomizer/species_pool.json")
OUTPUT_PATH = Path("src/data/randomizer/bst_table.h")


def main():
    if not SPECIES_POOL_PATH.exists():
        print(f"ERROR: {SPECIES_POOL_PATH} not found -- run fetch_species_data.py first.")
        return

    data = json.loads(SPECIES_POOL_PATH.read_text())
    entries = data["species"]

    # Indexed directly by species ID -- every constant with a known
    # BST, including forms (a trainer's original species could be any
    # of these).
    bst_by_species = {e["constant"]: e["bst"] for e in entries if e.get("bst") is not None}

    print(f"BST table: {len(bst_by_species)} species with known BST.")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("// Auto-generated by tools/randomizer/generate_bst_table.py -- do not hand edit.")
    lines.append("// Regenerate with: python3 tools/randomizer/generate_bst_table.py")
    lines.append("#ifndef GUARD_DATA_RANDOMIZER_BST_TABLE_H")
    lines.append("#define GUARD_DATA_RANDOMIZER_BST_TABLE_H")
    lines.append("")
    lines.append("#include \"constants/species.h\"")
    lines.append("")
    lines.append("// Indexed directly by species ID (same bound as SanitizeSpeciesId).")
    lines.append("// Unlisted species default to 0 -- callers should treat that as")
    lines.append("// \"unknown BST, don't apply the restriction\".")
    lines.append("static const u16 sSpeciesBST[NUM_SPECIES + 1] =")
    lines.append("{")
    for const, bst in bst_by_species.items():
        lines.append(f"    [{const}] = {bst},")
    lines.append("};")
    lines.append("")
    lines.append("#endif // GUARD_DATA_RANDOMIZER_BST_TABLE_H")
    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
