#!/usr/bin/env python3
"""
Generate src/data/randomizer/rival_pool.h -- for each base-stage
starter-eligible species, precompute its evolution line (up to 3 stages)
so the rival's randomly rolled species can display correctly-evolved
forms at each of their story battles.

Usage (from repo root):
    python3 tools/randomizer/generate_rival_pool.py
"""
import json
from pathlib import Path

SPECIES_POOL_PATH = Path("tools/randomizer/species_pool.json")
OUTPUT_PATH = Path("src/data/randomizer/rival_pool.h")

EXCLUDE_SUBSTRINGS = ["_MEGA", "_GMAX", "_PRIMAL", "_ETERNAMAX", "_TOTEM", "_ULTRA", "_COMPLETE"]


def main():
    if not SPECIES_POOL_PATH.exists():
        print(f"ERROR: {SPECIES_POOL_PATH} not found -- run fetch_species_data.py first.")
        return

    data = json.loads(SPECIES_POOL_PATH.read_text())
    entries = data["species"]

    # Canonical (non-form) constant for each api_name, so we can convert
    # api names back to SPECIES_ constants for the evolution chain.
    canonical_by_api_name = {}
    for e in entries:
        if not e["is_form"]:
            canonical_by_api_name.setdefault(e["api_name"], e["constant"])

    # Forward evolution map: api_name -> sorted list of api_names that
    # evolve directly from it (sorted for deterministic branch selection,
    # e.g. Eevee -- doesn't matter much since this runs once at build time).
    forward = {}
    for e in entries:
        if e["is_form"] or not e["evolves_from"]:
            continue
        forward.setdefault(e["evolves_from"], []).append(e["api_name"])
    for k in forward:
        forward[k].sort()

    # Base-stage eligible pool -- same eligibility as the starter pool.
    base_pool = []
    seen_api_names = set()
    for e in entries:
        if any(sub in e["constant"] for sub in EXCLUDE_SUBSTRINGS):
            continue
        if e["has_pre_evolution"]:
            continue
        api_name = e["api_name"]
        if api_name in seen_api_names:
            continue  # skip duplicate cosmetic/alternate forms (e.g. Unown letters)
        seen_api_names.add(api_name)
        base_pool.append(e)

    print(f"Base-stage eligible pool: {len(base_pool)} species.")

    lines_out = []
    missing_stage2 = 0
    missing_stage3 = 0
    for e in base_pool:
        stage0_api = e["api_name"]
        stage0_const = e["constant"]

        stage1_children = forward.get(stage0_api, [])
        stage1_api = stage1_children[0] if stage1_children else None
        stage1_const = canonical_by_api_name.get(stage1_api, stage0_const) if stage1_api else stage0_const
        if not stage1_api:
            missing_stage2 += 1

        stage2_children = forward.get(stage1_api, []) if stage1_api else []
        stage2_api = stage2_children[0] if stage2_children else None
        stage2_const = canonical_by_api_name.get(stage2_api, stage1_const) if stage2_api else stage1_const
        if not stage2_api:
            missing_stage3 += 1

        lines_out.append((stage0_const, stage1_const, stage2_const))

    print(f"  {missing_stage2} species have no 2nd stage (repeat stage 1).")
    print(f"  {missing_stage3} species have no 3rd stage (repeat stage 2 or 1).")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    out = []
    out.append("// Auto-generated by tools/randomizer/generate_rival_pool.py -- do not hand edit.")
    out.append("// Regenerate with: python3 tools/randomizer/generate_rival_pool.py")
    out.append("#ifndef GUARD_DATA_RANDOMIZER_RIVAL_POOL_H")
    out.append("#define GUARD_DATA_RANDOMIZER_RIVAL_POOL_H")
    out.append("")
    out.append("#include \"constants/species.h\"")
    out.append("")
    out.append("// Each row is {stage0 (base), stage1, stage2}, falling back to repeating")
    out.append("// the last known stage for species with fewer than 3 evolutions.")
    out.append("static const u16 sRandomizerRivalPool[][3] =")
    out.append("{")
    for s0, s1, s2 in lines_out:
        out.append(f"    {{{s0}, {s1}, {s2}}},")
    out.append("};")
    out.append("")
    out.append("#define RANDOMIZER_RIVAL_POOL_COUNT (sizeof(sRandomizerRivalPool) / sizeof(sRandomizerRivalPool[0]))")
    out.append("")
    out.append("#endif // GUARD_DATA_RANDOMIZER_RIVAL_POOL_H")

    OUTPUT_PATH.write_text("\n".join(out) + "\n")
    print(f"Wrote {OUTPUT_PATH} ({len(lines_out)} entries)")


if __name__ == "__main__":
    main()
