#!/usr/bin/env python3
"""
Generate src/data/randomizer/tm_pool.h -- TM/HM pocket items only, used
for randomizing TMs/HMs given via NPC scripts (giveitem/finditem,
including Trick House rewards), so a TM slot always becomes another
TM/HM rather than an arbitrary regular item.

Usage (from repo root):
    python3 tools/randomizer/generate_tm_pool.py
"""
import re
from pathlib import Path

ITEMS_H_PATH = Path("src/data/items.h")
OUTPUT_PATH = Path("src/data/randomizer/tm_pool.h")

ITEM_BLOCK_START = re.compile(r'\[(ITEM_[A-Z0-9_]+)\]\s*=')
POCKET_PATTERN = re.compile(r'\.pocket\s*=\s*(POCKET_[A-Z0-9_]+)')
NAME_PATTERN = re.compile(r'\.name\s*=\s*ITEM_NAME\("([^"]*)"\)')
DESC_PATTERN = re.compile(r'\.description\s*=\s*sQuestionMarksDesc')


def main():
    if not ITEMS_H_PATH.exists():
        print(f"ERROR: {ITEMS_H_PATH} not found -- run this from the repo root.")
        return

    content = ITEMS_H_PATH.read_text()
    matches = list(ITEM_BLOCK_START.finditer(content))

    pool = []
    seen = set()
    for i, m in enumerate(matches):
        name = m.group(1)
        if name in seen:
            continue
        window_end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        window = content[m.end():window_end]

        pocket_match = POCKET_PATTERN.search(window)
        pocket = pocket_match.group(1) if pocket_match else None
        if pocket != "POCKET_TM_HM":
            continue

        name_match = NAME_PATTERN.search(window)
        item_name = name_match.group(1) if name_match else ""
        if not item_name.strip():
            continue
        if DESC_PATTERN.search(window):
            continue  # placeholder "???" description, not filled in upstream

        seen.add(name)
        pool.append(name)

    print(f"TM/HM pool: {len(pool)} eligible TMs/HMs.")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("// Auto-generated by tools/randomizer/generate_tm_pool.py -- do not hand edit.")
    lines.append("// Regenerate with: python3 tools/randomizer/generate_tm_pool.py")
    lines.append("#ifndef GUARD_DATA_RANDOMIZER_TM_POOL_H")
    lines.append("#define GUARD_DATA_RANDOMIZER_TM_POOL_H")
    lines.append("")
    lines.append("#include \"constants/items.h\"")
    lines.append("")
    lines.append("static const u16 sRandomizerTMPool[] =")
    lines.append("{")
    for name in pool:
        lines.append(f"    {name},")
    lines.append("};")
    lines.append("")
    lines.append("#define RANDOMIZER_TM_POOL_COUNT (sizeof(sRandomizerTMPool) / sizeof(sRandomizerTMPool[0]))")
    lines.append("")
    lines.append("#endif // GUARD_DATA_RANDOMIZER_TM_POOL_H")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
