#!/usr/bin/env python3
"""
Generate src/data/randomizer/item_pool.h -- the pool of items eligible
for item-ball randomization: POCKET_ITEMS, POCKET_POKE_BALLS, and
POCKET_TM_HM only. Key items and berries are never included, so they
can never be placed into a randomized slot.

Usage (from repo root):
    python3 tools/randomizer/generate_item_pool.py
"""
import re
from pathlib import Path

ITEMS_H_PATH = Path("src/data/items.h")
OUTPUT_PATH = Path("src/data/randomizer/item_pool.h")

ITEM_BLOCK_START = re.compile(r'\[(ITEM_[A-Z0-9_]+)\]\s*=')
POCKET_PATTERN = re.compile(r'\.pocket\s*=\s*(POCKET_[A-Z0-9_]+)')
NAME_PATTERN = re.compile(r'\.name\s*=\s*ITEM_NAME\("([^"]*)"\)')
DESC_PATTERN = re.compile(r'\.description\s*=\s*sQuestionMarksDesc')

SAFE_POCKETS = {"POCKET_ITEMS", "POCKET_TM_HM"}  # Poké Balls, berries intentionally excluded

# Specific items included despite their pocket not being generally safe --
# Sitrus Berry is a genuinely useful, non-gimmicky item worth having in
# the pool even though berries are otherwise excluded entirely.
EXTRA_INCLUDED_ITEMS = {"ITEM_SITRUS_BERRY"}


def main():
    if not ITEMS_H_PATH.exists():
        print(f"ERROR: {ITEMS_H_PATH} not found -- run this from the repo root.")
        return

    content = ITEMS_H_PATH.read_text()
    matches = list(ITEM_BLOCK_START.finditer(content))

    pool = []
    seen = set()
    for i, m in enumerate(matches):
        name = m.group(1)
        if name in seen:
            continue  # some constants alias others (e.g. pre-Gen VI names)
        window_end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        window = content[m.end():window_end]

        pocket_match = POCKET_PATTERN.search(window)
        pocket = pocket_match.group(1) if pocket_match else None
        if pocket not in SAFE_POCKETS and name not in EXTRA_INCLUDED_ITEMS:
            continue

        name_match = NAME_PATTERN.search(window)
        item_name = name_match.group(1) if name_match else ""
        if not item_name.strip():
            continue
        if DESC_PATTERN.search(window):
            continue  # placeholder "???" description, not filled in upstream  # skip placeholder/unnamed entries

        seen.add(name)
        pool.append(name)

    print(f"Item pool: {len(pool)} eligible items (Items/Poké Balls/TM-HM pockets).")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("// Auto-generated by tools/randomizer/generate_item_pool.py -- do not hand edit.")
    lines.append("// Regenerate with: python3 tools/randomizer/generate_item_pool.py")
    lines.append("#ifndef GUARD_DATA_RANDOMIZER_ITEM_POOL_H")
    lines.append("#define GUARD_DATA_RANDOMIZER_ITEM_POOL_H")
    lines.append("")
    lines.append("#include \"constants/items.h\"")
    lines.append("")
    lines.append("static const u16 sRandomizerItemPool[] =")
    lines.append("{")
    for name in pool:
        lines.append(f"    {name},")
    lines.append("};")
    lines.append("")
    lines.append("#define RANDOMIZER_ITEM_POOL_COUNT (sizeof(sRandomizerItemPool) / sizeof(sRandomizerItemPool[0]))")
    lines.append("")
    lines.append("#endif // GUARD_DATA_RANDOMIZER_ITEM_POOL_H")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
