#!/usr/bin/env python3
"""
Generate src/data/randomizer/starter_pool.h -- the full pool of
base-stage-only species (regular + legendary/mythical, minus battle-only
forms) that the runtime per-save starter roll picks from.

This REPLACES the old randomize_starters.py approach of picking 3
species at build time -- now the whole pool is baked into the ROM, and
the actual pick of 3 happens at runtime in new_game.c, once per save.

Usage (from repo root):
    python3 tools/randomizer/generate_starter_pool.py
"""
import json
from pathlib import Path

SPECIES_POOL_PATH = Path("tools/randomizer/species_pool.json")
OUTPUT_PATH = Path("src/data/randomizer/starter_pool.h")

EXCLUDE_SUBSTRINGS = ["_MEGA", "_GMAX", "_PRIMAL", "_ETERNAMAX", "_TOTEM", "_ULTRA", "_COMPLETE"]


def main():
    if not SPECIES_POOL_PATH.exists():
        print(f"ERROR: {SPECIES_POOL_PATH} not found -- run fetch_species_data.py first.")
        return

    data = json.loads(SPECIES_POOL_PATH.read_text())
    pool = []
    seen_api_names = set()
    for entry in data["species"]:
        const = entry["constant"]
        if any(sub in const for sub in EXCLUDE_SUBSTRINGS):
            continue
        if entry.get("has_pre_evolution", False):
            continue
        api_name = entry["api_name"]
        if api_name in seen_api_names:
            continue  # skip duplicate cosmetic/alternate forms (e.g. Unown letters)
        seen_api_names.add(api_name)
        pool.append(const)

    print(f"Base-stage eligible pool: {len(pool)} species.")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("// Auto-generated by tools/randomizer/generate_starter_pool.py -- do not hand edit.")
    lines.append("// Regenerate with: python3 tools/randomizer/generate_starter_pool.py")
    lines.append("#ifndef GUARD_DATA_RANDOMIZER_STARTER_POOL_H")
    lines.append("#define GUARD_DATA_RANDOMIZER_STARTER_POOL_H")
    lines.append("")
    lines.append("#include \"constants/species.h\"")
    lines.append("")
    lines.append("static const u16 sRandomizerStarterPool[] =")
    lines.append("{")
    for const in pool:
        lines.append(f"    {const},")
    lines.append("};")
    lines.append("")
    lines.append("#define RANDOMIZER_STARTER_POOL_COUNT (sizeof(sRandomizerStarterPool) / sizeof(sRandomizerStarterPool[0]))")
    lines.append("")
    lines.append("#endif // GUARD_DATA_RANDOMIZER_STARTER_POOL_H")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
