#!/usr/bin/env python3
"""
Generate src/data/randomizer/species_family_table.h -- for every species,
the "root" (base-stage) species of its evolution family, by walking
evolves_from backward to the ancestor with no further pre-evolution.

Used so per-save ability randomization is consistent across an entire
evolution line (e.g. Bulbasaur/Ivysaur/Venusaur all hash on Bulbasaur,
so evolving never changes your ability), rather than each stage of a
line rolling an independent ability.

Usage (from repo root):
    python3 tools/randomizer/generate_species_family_table.py
"""
import json
from pathlib import Path

SPECIES_POOL_PATH = Path("tools/randomizer/species_pool.json")
OUTPUT_PATH = Path("src/data/randomizer/species_family_table.h")


def main():
    if not SPECIES_POOL_PATH.exists():
        print(f"ERROR: {SPECIES_POOL_PATH} not found -- run fetch_species_data.py first.")
        return

    data = json.loads(SPECIES_POOL_PATH.read_text())
    entries = data["species"]

    by_constant = {e["constant"]: e for e in entries}

    # Canonical (non-form) constant for each api_name, needed to resolve
    # evolves_from (an api_name string) back into a real SPECIES_ constant.
    canonical_by_api_name = {}
    for e in entries:
        if not e["is_form"]:
            canonical_by_api_name.setdefault(e["api_name"], e["constant"])

    def parent_constant(entry):
        if not entry["evolves_from"]:
            return None
        return canonical_by_api_name.get(entry["evolves_from"])

    family_root = {}
    for e in entries:
        const = e["constant"]
        cur = e
        visited = set()
        while True:
            parent_const = parent_constant(cur)
            if not parent_const or parent_const in visited or parent_const not in by_constant:
                break
            visited.add(parent_const)
            cur = by_constant[parent_const]
        family_root[const] = cur["constant"]

    changed = sum(1 for c, root in family_root.items() if c != root)
    print(f"Computed family roots for {len(family_root)} species ({changed} are non-root members of a line).")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("// Auto-generated by tools/randomizer/generate_species_family_table.py -- do not hand edit.")
    lines.append("// Regenerate with: python3 tools/randomizer/generate_species_family_table.py")
    lines.append("#ifndef GUARD_DATA_RANDOMIZER_SPECIES_FAMILY_TABLE_H")
    lines.append("#define GUARD_DATA_RANDOMIZER_SPECIES_FAMILY_TABLE_H")
    lines.append("")
    lines.append("#include \"constants/species.h\"")
    lines.append("")
    lines.append("// Indexed directly by species ID (same bound as SanitizeSpeciesId).")
    lines.append("// Unlisted species default to 0 (SPECIES_NONE); callers should treat")
    lines.append("// that as \"no family data, use the species itself\".")
    lines.append("static const u16 sSpeciesFamilyRoot[NUM_SPECIES + 1] =")
    lines.append("{")
    for const, root in family_root.items():
        lines.append(f"    [{const}] = {root},")
    lines.append("};")
    lines.append("")
    lines.append("#endif // GUARD_DATA_RANDOMIZER_SPECIES_FAMILY_TABLE_H")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
