#!/usr/bin/env python3
"""
Generate src/data/randomizer/ability_pool.h -- the pool of abilities
eligible for per-save runtime substitution in GetSpeciesAbility
(src/pokemon.c). Replaces the old build-time approach
(randomize_abilities.py), which is no longer used.

Usage (from repo root):
    python3 tools/randomizer/generate_ability_pool.py
"""
import re
from pathlib import Path

ABILITIES_H_PATH = Path("include/constants/abilities.h")
OUTPUT_PATH = Path("src/data/randomizer/ability_pool.h")

ABILITY_EXCLUDED = {"ABILITY_NONE", "ABILITY_WONDER_GUARD"}


def main():
    if not ABILITIES_H_PATH.exists():
        print(f"ERROR: {ABILITIES_H_PATH} not found -- run this from the repo root.")
        return

    pattern = re.compile(r'^\s*(ABILITY_[A-Z0-9_]+)\s*=\s*\d+,?')
    pool = []
    with open(ABILITIES_H_PATH) as f:
        for line in f:
            m = pattern.match(line)
            if m and m.group(1) not in ABILITY_EXCLUDED:
                pool.append(m.group(1))

    print(f"Ability pool: {len(pool)} candidates.")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("// Auto-generated by tools/randomizer/generate_ability_pool.py -- do not hand edit.")
    lines.append("// Regenerate with: python3 tools/randomizer/generate_ability_pool.py")
    lines.append("#ifndef GUARD_DATA_RANDOMIZER_ABILITY_POOL_H")
    lines.append("#define GUARD_DATA_RANDOMIZER_ABILITY_POOL_H")
    lines.append("")
    lines.append("#include \"constants/abilities.h\"")
    lines.append("")
    lines.append("static const u16 sRandomizerAbilityPool[] =")
    lines.append("{")
    for name in pool:
        lines.append(f"    {name},")
    lines.append("};")
    lines.append("")
    lines.append("#define RANDOMIZER_ABILITY_POOL_COUNT (sizeof(sRandomizerAbilityPool) / sizeof(sRandomizerAbilityPool[0]))")
    lines.append("")
    lines.append("#endif // GUARD_DATA_RANDOMIZER_ABILITY_POOL_H")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
