#!/usr/bin/env python3
"""
Generate src/data/randomizer/wild_pool.h -- the full pool of regular
(non-legendary/mythical) species, minus battle-only forms, used by the
runtime per-save wild encounter substitution in wild_encounter.c.

Unlike the starter pool, this is NOT restricted to base-stage species --
a wild Manectric is perfectly normal, just not a starter.

Usage (from repo root):
    python3 tools/randomizer/generate_wild_pool.py
"""
import json
from pathlib import Path

SPECIES_POOL_PATH = Path("tools/randomizer/species_pool.json")
OUTPUT_PATH = Path("src/data/randomizer/wild_pool.h")

EXCLUDE_SUBSTRINGS = ["_MEGA", "_GMAX", "_PRIMAL", "_ETERNAMAX", "_TOTEM", "_ULTRA", "_COMPLETE"]

# Paradox Pokemon (Gen 9) -- not flagged as legendary/mythical by PokeAPI,
# so excluded by an explicit constant list instead.
EXCLUDE_PARADOX = {
    "SPECIES_GREAT_TUSK", "SPECIES_SCREAM_TAIL", "SPECIES_BRUTE_BONNET",
    "SPECIES_FLUTTER_MANE", "SPECIES_SLITHER_WING", "SPECIES_SANDY_SHOCKS",
    "SPECIES_IRON_TREADS", "SPECIES_IRON_BUNDLE", "SPECIES_IRON_HANDS",
    "SPECIES_IRON_JUGULIS", "SPECIES_IRON_MOTH", "SPECIES_IRON_THORNS",
    "SPECIES_ROARING_MOON", "SPECIES_IRON_VALIANT", "SPECIES_WALKING_WAKE",
    "SPECIES_IRON_LEAVES", "SPECIES_GOUGING_FIRE", "SPECIES_RAGING_BOLT",
    "SPECIES_IRON_BOULDER", "SPECIES_IRON_CROWN",
}

# Ultra Beasts (Gen 7) -- not flagged as legendary/mythical by PokeAPI,
# so excluded by an explicit constant list instead. Allowed for
# legendary-category scripted encounters (legendary_pool.h), same as
# legendaries/mythicals/Paradox -- just never a regular wild substitute.
EXCLUDE_ULTRA_BEASTS = {
    "SPECIES_NIHILEGO", "SPECIES_BUZZWOLE", "SPECIES_PHEROMOSA",
    "SPECIES_XURKITREE", "SPECIES_CELESTEELA", "SPECIES_KARTANA",
    "SPECIES_GUZZLORD", "SPECIES_POIPOLE", "SPECIES_NAGANADEL",
    "SPECIES_STAKATAKA", "SPECIES_BLACEPHALON",
}


def main():
    if not SPECIES_POOL_PATH.exists():
        print(f"ERROR: {SPECIES_POOL_PATH} not found -- run fetch_species_data.py first.")
        return

    data = json.loads(SPECIES_POOL_PATH.read_text())
    pool = []
    seen_api_names = set()
    for entry in data["species"]:
        const = entry["constant"]
        if any(sub in const for sub in EXCLUDE_SUBSTRINGS):
            continue
        if entry["legendary"] or entry["mythical"]:
            continue
        if const in EXCLUDE_PARADOX:
            continue
        if const in EXCLUDE_ULTRA_BEASTS:
            continue
        api_name = entry["api_name"]
        if api_name in seen_api_names:
            continue  # skip duplicate cosmetic/alternate forms (e.g. Unown letters)
        seen_api_names.add(api_name)
        pool.append(const)

    print(f"Wild-encounter eligible pool: {len(pool)} species.")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("// Auto-generated by tools/randomizer/generate_wild_pool.py -- do not hand edit.")
    lines.append("// Regenerate with: python3 tools/randomizer/generate_wild_pool.py")
    lines.append("#ifndef GUARD_DATA_RANDOMIZER_WILD_POOL_H")
    lines.append("#define GUARD_DATA_RANDOMIZER_WILD_POOL_H")
    lines.append("")
    lines.append("#include \"constants/species.h\"")
    lines.append("")
    lines.append("static const u16 sRandomizerWildPool[] =")
    lines.append("{")
    for const in pool:
        lines.append(f"    {const},")
    lines.append("};")
    lines.append("")
    lines.append("#define RANDOMIZER_WILD_POOL_COUNT (sizeof(sRandomizerWildPool) / sizeof(sRandomizerWildPool[0]))")
    lines.append("")
    lines.append("#endif // GUARD_DATA_RANDOMIZER_WILD_POOL_H")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
