#!/usr/bin/env python3
"""
Generate src/data/randomizer/item_pool.h -- the pool of items eligible
for item-ball randomization: POCKET_ITEMS, POCKET_POKE_BALLS, and
POCKET_TM_HM only. Key items and berries are never included, so they
can never be placed into a randomized slot.

Usage (from repo root):
    python3 tools/randomizer/generate_item_pool.py
"""
import re
from pathlib import Path

ITEMS_H_PATH = Path("src/data/items.h")
OUTPUT_PATH = Path("src/data/randomizer/item_pool.h")

ITEM_BLOCK_START = re.compile(r'\[(ITEM_[A-Z0-9_]+)\]\s*=')
POCKET_PATTERN = re.compile(r'\.pocket\s*=\s*(POCKET_[A-Z0-9_]+)')
NAME_PATTERN = re.compile(r'\.name\s*=\s*ITEM_NAME\("([^"]*)"\)')
DESC_PATTERN = re.compile(r'\.description\s*=\s*sQuestionMarksDesc')
SORT_TYPE_PATTERN = re.compile(r'\.sortType\s*=\s*(ITEM_TYPE_[A-Z0-9_]+)')

SAFE_POCKETS = {"POCKET_ITEMS", "POCKET_TM_HM"}  # Poké Balls, berries intentionally excluded

# Specific items included despite their pocket not being generally safe --
# Sitrus Berry is a genuinely useful, non-gimmicky item worth having in
# the pool even though berries are otherwise excluded entirely.
EXTRA_INCLUDED_ITEMS = {"ITEM_SITRUS_BERRY"}

# Battle-gimmick item categories -- identified by their .sortType, since
# name-substring matching is unreliable (e.g. "ITE" as a substring would
# false-positive on unrelated items like White Herb).
EXCLUDE_SORT_TYPES = {"ITEM_TYPE_MEGA_STONE", "ITEM_TYPE_Z_CRYSTAL", "ITEM_TYPE_TERA_SHARD"}

# Rare Candy / Exp Candies -- direct level-up items, and Dynamax-related
# items -- all excluded by exact constant name instead, since they're
# each a small, specific set rather than sharing one sortType.
EXCLUDE_SPECIFIC_ITEMS = {
    "ITEM_RARE_CANDY",
    "ITEM_EXP_CANDY_XS", "ITEM_EXP_CANDY_S", "ITEM_EXP_CANDY_M",
    "ITEM_EXP_CANDY_L", "ITEM_EXP_CANDY_XL",
    "ITEM_DYNAMAX_CANDY", "ITEM_MAX_MUSHROOMS", "ITEM_DYNAMAX_BAND",
    "ITEM_DYNITE_ORE",
    # Apricorns -- only used for the Apricorn Ball crafting minigame,
    # not implemented/relevant here.
    "ITEM_RED_APRICORN", "ITEM_BLUE_APRICORN", "ITEM_YELLOW_APRICORN",
    "ITEM_GREEN_APRICORN", "ITEM_PINK_APRICORN", "ITEM_WHITE_APRICORN",
    "ITEM_BLACK_APRICORN",
    # Memories -- only used to change Silvally's type, which isn't
    # obtainable/relevant in this hack.
    "ITEM_FIRE_MEMORY", "ITEM_WATER_MEMORY", "ITEM_ELECTRIC_MEMORY",
    "ITEM_GRASS_MEMORY", "ITEM_ICE_MEMORY", "ITEM_FIGHTING_MEMORY",
    "ITEM_POISON_MEMORY", "ITEM_GROUND_MEMORY", "ITEM_FLYING_MEMORY",
    "ITEM_PSYCHIC_MEMORY", "ITEM_BUG_MEMORY", "ITEM_ROCK_MEMORY",
    "ITEM_GHOST_MEMORY", "ITEM_DRAGON_MEMORY", "ITEM_DARK_MEMORY",
    "ITEM_STEEL_MEMORY", "ITEM_FAIRY_MEMORY",
}


def main():
    if not ITEMS_H_PATH.exists():
        print(f"ERROR: {ITEMS_H_PATH} not found -- run this from the repo root.")
        return

    content = ITEMS_H_PATH.read_text()
    matches = list(ITEM_BLOCK_START.finditer(content))

    pool = []
    seen = set()
    for i, m in enumerate(matches):
        name = m.group(1)
        if name in seen:
            continue  # some constants alias others (e.g. pre-Gen VI names)
        window_end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        window = content[m.end():window_end]

        pocket_match = POCKET_PATTERN.search(window)
        pocket = pocket_match.group(1) if pocket_match else None
        if pocket not in SAFE_POCKETS and name not in EXTRA_INCLUDED_ITEMS:
            continue
        if name in EXCLUDE_SPECIFIC_ITEMS:
            continue
        sort_type_match = SORT_TYPE_PATTERN.search(window)
        sort_type = sort_type_match.group(1) if sort_type_match else None
        if sort_type in EXCLUDE_SORT_TYPES:
            continue

        name_match = NAME_PATTERN.search(window)
        item_name = name_match.group(1) if name_match else ""
        if not item_name.strip():
            continue
        if DESC_PATTERN.search(window):
            continue  # placeholder "???" description, not filled in upstream  # skip placeholder/unnamed entries

        seen.add(name)
        pool.append(name)

    print(f"Item pool: {len(pool)} eligible items (Items/Poké Balls/TM-HM pockets).")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("// Auto-generated by tools/randomizer/generate_item_pool.py -- do not hand edit.")
    lines.append("// Regenerate with: python3 tools/randomizer/generate_item_pool.py")
    lines.append("#ifndef GUARD_DATA_RANDOMIZER_ITEM_POOL_H")
    lines.append("#define GUARD_DATA_RANDOMIZER_ITEM_POOL_H")
    lines.append("")
    lines.append("#include \"constants/items.h\"")
    lines.append("")
    lines.append("static const u16 sRandomizerItemPool[] =")
    lines.append("{")
    for name in pool:
        lines.append(f"    {name},")
    lines.append("};")
    lines.append("")
    lines.append("#define RANDOMIZER_ITEM_POOL_COUNT (sizeof(sRandomizerItemPool) / sizeof(sRandomizerItemPool[0]))")
    lines.append("")
    lines.append("#endif // GUARD_DATA_RANDOMIZER_ITEM_POOL_H")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
