#!/usr/bin/env python3
"""
Generate src/data/randomizer/legendary_pool.h -- for scripted legendary
encounters (Regirock/Regice/Registeel, and any other setwildbattle-driven
encounter whose original species is itself legendary/mythical/Paradox),
this provides:
  - sRandomizerLegendaryPool[]: the substitute pool (legendary/mythical/
    Paradox species only, minus battle-only forms), used when the
    ORIGINAL species being spawned is itself in this category.
  - sSpeciesIsLegendary[]: a lookup table (indexed by species ID, same
    bound as SanitizeSpeciesId) used to detect whether a given original
    species falls into this category at all, so a scripted encounter for
    a regular species (if any exist) still uses the normal wild pool
    instead.
Usage (from repo root):
    python3 tools/randomizer/generate_legendary_pool.py
"""
import json
from pathlib import Path

SPECIES_POOL_PATH = Path("tools/randomizer/species_pool.json")
OUTPUT_PATH = Path("src/data/randomizer/legendary_pool.h")

EXCLUDE_SUBSTRINGS = ["_MEGA", "_GMAX", "_PRIMAL", "_ETERNAMAX", "_TOTEM", "_ULTRA", "_COMPLETE"]

# Paradox Pokemon (Gen 9) -- not flagged as legendary/mythical by PokeAPI,
# so included by an explicit constant list instead. Mirrors the same set
# excluded from the wild pool in generate_wild_pool.py.
PARADOX_SPECIES = {
    "SPECIES_GREAT_TUSK", "SPECIES_SCREAM_TAIL", "SPECIES_BRUTE_BONNET",
    "SPECIES_FLUTTER_MANE", "SPECIES_SLITHER_WING", "SPECIES_SANDY_SHOCKS",
    "SPECIES_IRON_TREADS", "SPECIES_IRON_BUNDLE", "SPECIES_IRON_HANDS",
    "SPECIES_IRON_JUGULIS", "SPECIES_IRON_MOTH", "SPECIES_IRON_THORNS",
    "SPECIES_ROARING_MOON", "SPECIES_IRON_VALIANT", "SPECIES_WALKING_WAKE",
    "SPECIES_IRON_LEAVES", "SPECIES_GOUGING_FIRE", "SPECIES_RAGING_BOLT",
    "SPECIES_IRON_BOULDER", "SPECIES_IRON_CROWN",
}

# Ultra Beasts (Gen 7) -- not flagged as legendary/mythical by PokeAPI,
# so included by an explicit constant list instead. Mirrors the same
# set excluded from the wild pool in generate_wild_pool.py.
ULTRA_BEAST_SPECIES = {
    "SPECIES_NIHILEGO", "SPECIES_BUZZWOLE", "SPECIES_PHEROMOSA",
    "SPECIES_XURKITREE", "SPECIES_CELESTEELA", "SPECIES_KARTANA",
    "SPECIES_GUZZLORD", "SPECIES_POIPOLE", "SPECIES_NAGANADEL",
    "SPECIES_STAKATAKA", "SPECIES_BLACEPHALON",
}


def is_legendary_category(entry):
    return (entry["legendary"] or entry["mythical"]
            or entry["constant"] in PARADOX_SPECIES
            or entry["constant"] in ULTRA_BEAST_SPECIES)


def main():
    if not SPECIES_POOL_PATH.exists():
        print(f"ERROR: {SPECIES_POOL_PATH} not found -- run fetch_species_data.py first.")
        return

    data = json.loads(SPECIES_POOL_PATH.read_text())
    entries = data["species"]

    # Substitute pool: legendary/mythical/Paradox only, minus battle-only
    # forms, deduped by api_name (matching the other pool generators).
    pool = []
    seen_api_names = set()
    for entry in entries:
        const = entry["constant"]
        if any(sub in const for sub in EXCLUDE_SUBSTRINGS):
            continue
        if not is_legendary_category(entry):
            continue
        api_name = entry["api_name"]
        if api_name in seen_api_names:
            continue
        seen_api_names.add(api_name)
        pool.append(const)

    # Lookup table: every species constant (including forms) that's
    # legendary/mythical/Paradox, so any original species passed to
    # setwildbattle can be checked, not just the deduped pool entries.
    lookup = [entry["constant"] for entry in entries if is_legendary_category(entry)]

    print(f"Legendary/mythical/Paradox substitute pool: {len(pool)} species.")
    print(f"Legendary/mythical/Paradox lookup table: {len(lookup)} entries.")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("// Auto-generated by tools/randomizer/generate_legendary_pool.py -- do not hand edit.")
    lines.append("// Regenerate with: python3 tools/randomizer/generate_legendary_pool.py")
    lines.append("#ifndef GUARD_DATA_RANDOMIZER_LEGENDARY_POOL_H")
    lines.append("#define GUARD_DATA_RANDOMIZER_LEGENDARY_POOL_H")
    lines.append("")
    lines.append("#include \"constants/species.h\"")
    lines.append("")
    lines.append("static const u16 sRandomizerLegendaryPool[] =")
    lines.append("{")
    for name in pool:
        lines.append(f"    {name},")
    lines.append("};")
    lines.append("")
    lines.append("#define RANDOMIZER_LEGENDARY_POOL_COUNT (sizeof(sRandomizerLegendaryPool) / sizeof(sRandomizerLegendaryPool[0]))")
    lines.append("")
    lines.append("// Indexed directly by species ID (same bound as SanitizeSpeciesId).")
    lines.append("// TRUE if that species is legendary/mythical/Paradox; unlisted")
    lines.append("// species default to FALSE (regular species).")
    lines.append("static const bool8 sSpeciesIsLegendary[NUM_SPECIES + 1] =")
    lines.append("{")
    for name in lookup:
        lines.append(f"    [{name}] = TRUE,")
    lines.append("};")
    lines.append("")
    lines.append("#endif // GUARD_DATA_RANDOMIZER_LEGENDARY_POOL_H")
    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
