#!/usr/bin/env python3
"""
Generate src/data/randomizer/move_pool.h -- move pools for per-save
runtime learnset randomization in GetSpeciesLevelUpLearnset
(src/pokemon.c). Replaces the old build-time approach
(randomize_learnsets.py), which is no longer used.

Two pools:
- sRandomizerMovePool: every eligible move (used for ordinary substitution)
- sRandomizerDamagingMovePool: subset that deals real damage (used for
  the no-damage-move safety fix)

Usage (from repo root):
    python3 tools/randomizer/generate_move_pool.py
"""
import re
from pathlib import Path

MOVES_INFO_PATH = Path("src/data/moves_info.h")
MOVES_H_PATH = Path("include/constants/moves.h")
OUTPUT_PATH = Path("src/data/randomizer/move_pool.h")

MOVE_BLOCK_START = re.compile(r'\[(MOVE_[A-Z0-9_]+)\]\s*=')
POWER_PATTERN = re.compile(r'\.power\s*=\s*(\d+)')
EFFECT_PATTERN = re.compile(r'\.effect\s*=\s*(EFFECT_[A-Z0-9_]+)')

NEVER_FAINTS_EFFECT = "EFFECT_FALSE_SWIPE"

# Pokémon: Let's Go, Pikachu!/Eevee! and Partner Power (Isle of Armor)
# signature moves -- don't make sense outside those specific event/partner
# mechanics.
EXTRA_EXCLUDED_MOVES = {
    "MOVE_PIKA_PAPOW", "MOVE_VEEVEE_VOLLEY",
    "MOVE_ZIPPY_ZAP", "MOVE_FLOATY_FALL", "MOVE_SPLISHY_SPLASH",
    "MOVE_BOUNCY_BUBBLE", "MOVE_BUZZY_BUZZ", "MOVE_SIZZLY_SLIDE",
    "MOVE_GLITZY_GLOW", "MOVE_BADDY_BAD", "MOVE_SAPPY_SEED",
    "MOVE_FREEZY_FROST", "MOVE_SPARKLY_SWIRL",
    # HM moves -- excluded from the level-up learnset randomizer so a
    # Pokemon never randomly "learns" an HM via leveling up.
    "MOVE_CUT", "MOVE_FLY", "MOVE_SURF", "MOVE_STRENGTH", "MOVE_FLASH",
    "MOVE_ROCK_SMASH", "MOVE_WATERFALL", "MOVE_DIVE",
}


def load_gimmick_moves():
    """
    Z-moves, Max moves, and G-Max moves -- grouped in one contiguous
    block at the tail of the MOVE_ enum, starting at FIRST_Z_MOVE.
    """
    lines = MOVES_H_PATH.read_text().splitlines()
    move_pattern = re.compile(r'^\s*(MOVE_[A-Z0-9_]+)')
    gimmick = set()
    started = False
    for line in lines:
        if not started:
            if "FIRST_Z_MOVE" in line:
                started = True
            else:
                continue
        m = move_pattern.match(line)
        if m:
            gimmick.add(m.group(1))
    return gimmick


def load_move_pools():
    gimmick_moves = load_gimmick_moves()
    content = MOVES_INFO_PATH.read_text()
    matches = list(MOVE_BLOCK_START.finditer(content))
    damaging = []
    all_moves = []
    for i, m in enumerate(matches):
        move_const = m.group(1)
        if move_const == "MOVE_NONE" or move_const in gimmick_moves or move_const in EXTRA_EXCLUDED_MOVES:
            continue
        window_end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        window = content[m.end():window_end]
        power_match = POWER_PATTERN.search(window)
        power = int(power_match.group(1)) if power_match else 0
        effect_match = EFFECT_PATTERN.search(window)
        effect = effect_match.group(1) if effect_match else None
        all_moves.append(move_const)
        if power > 0 and effect != NEVER_FAINTS_EFFECT:
            damaging.append(move_const)
    return all_moves, damaging


def main():
    if not MOVES_INFO_PATH.exists() or not MOVES_H_PATH.exists():
        print("ERROR: required files not found -- run this from the repo root.")
        return

    all_moves, damaging = load_move_pools()
    print(f"Move pool: {len(all_moves)} total, {len(damaging)} damaging.")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("// Auto-generated by tools/randomizer/generate_move_pool.py -- do not hand edit.")
    lines.append("// Regenerate with: python3 tools/randomizer/generate_move_pool.py")
    lines.append("#ifndef GUARD_DATA_RANDOMIZER_MOVE_POOL_H")
    lines.append("#define GUARD_DATA_RANDOMIZER_MOVE_POOL_H")
    lines.append("")
    lines.append("#include \"constants/moves.h\"")
    lines.append("")
    lines.append("static const u16 sRandomizerMovePool[] =")
    lines.append("{")
    for name in all_moves:
        lines.append(f"    {name},")
    lines.append("};")
    lines.append("")
    lines.append("static const u16 sRandomizerDamagingMovePool[] =")
    lines.append("{")
    for name in damaging:
        lines.append(f"    {name},")
    lines.append("};")
    lines.append("")
    lines.append("#define RANDOMIZER_MOVE_POOL_COUNT (sizeof(sRandomizerMovePool) / sizeof(sRandomizerMovePool[0]))")
    lines.append("#define RANDOMIZER_DAMAGING_MOVE_POOL_COUNT (sizeof(sRandomizerDamagingMovePool) / sizeof(sRandomizerDamagingMovePool[0]))")
    lines.append("")
    lines.append("// O(1) lookup: is a given (already-substituted) move damaging?")
    lines.append("// Indexed directly by move ID, same bound as MOVES_COUNT_ALL.")
    lines.append("static const u8 sMoveIsDamaging[MOVES_COUNT_ALL] =")
    lines.append("{")
    for name in damaging:
        lines.append(f"    [{name}] = TRUE,")
    lines.append("};")
    lines.append("")
    lines.append("#endif // GUARD_DATA_RANDOMIZER_MOVE_POOL_H")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
